name: Build ipfs w3auth pinning service(baitech)

on:
  workflow_dispatch:
  push:
    branches: [ "baitech" ]

jobs:
  build:
    if: github.repository == 'decooio/ipfs-w3auth-pinning-service'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MAXM_PAT_PACKAGES }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/decooio/ipfs-w3auth-pinning-service-baitech:latest, ghcr.io/decooio/ipfs-w3auth-pinning-service-baitech:${{ steps.date.outputs.date }}
